version: '3.8'

services:
  db:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: django_user
      MYSQL_PASSWORD: djangopassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - backend

  web:
    container_name: django_cont
    image: muhammadelmansi/depi_final
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=djangopassword
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - 8000:8000
    networks:
      - backend
      - frontend

volumes:
  db_data:

networks:
  backend:
  frontend:
